# Generated by Django 4.2.4 on 2023-08-09 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gptkey',
            field=models.CharField(default='xxx', max_length=255),
        ),
    ]
