# Generated by Django 4.0.3 on 2023-08-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_paid_std',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_paid_ult',
            field=models.BooleanField(default=False),
        ),
    ]
