# Generated by Django 4.2.4 on 2023-08-22 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_is_paid_std_user_is_paid_ult'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='paid_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
