# Generated by Django 4.2.4 on 2023-08-30 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gptkey',
            field=models.CharField(default='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', max_length=255),
        ),
    ]
